print("Введите этапы развития человека по порядку:")
stage1=input("1-й этап: ")
stage2=input("2-й этап: ")
stage3=input("3-й этап: ")
stage4=input("4-й этап: ")
stage5=input("5-й этап: ")
stage6=input("6-й этап: ")
stage7=input("7-й этап: ")
print(stage1, stage2, stage3, stage4, stage5, stage6, stage7, sep=' => ')